# File: .github/workflows/test-action.yml
name: Test Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 25f1001318@ds.study.iitm.ac.in
        run: echo "Hello, world!"
